export const TOGGLE_ADD_USER = 'TOGGLE_ADD_USER'
export const CHANGE_HANDLER_ADD_USER = 'CHANGE_HANDLER_ADD_USER'
export const ADD_USER = 'ADD_USER'
export const CANCEL_ADD_USER = 'CANCEL_ADD_USER'

export const TOGGLE_EDIT_USER = 'TOGGLE_EDIT_USER'
export const CHANGE_HANDLER_EDIT_USER = 'CHANGE_HANDLER_EDIT_USER'
export const SAVE_EDIT_USER = 'SAVE_EDIT_USER'
export const CANCEL_EDIT_USER = 'CANCEL_EDIT_USER'

export const REMOVAL_USER = 'REMOVAL_USER'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'